spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logger
    username: postgres
    password: pass
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        search:
          default:
            indexmanager: elasticsearch
            elasticsearch:
              host: http://localhost:9200
              index_schema_management_strategy: drop-and-create
              required_index_status: yellow
